# Generated by Django 4.0.2 on 2022-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applications',
            constraint=models.UniqueConstraint(fields=('applicant', 'job'), name='unique_constrain'),
        ),
    ]
